#!/usr/bin/env bash
set -e

APP_NAME="RunnerBar"
VERSION="0.7.0"
OUT_DIR="dist"

# ---------------------------------------------------------------------------
# Phase 4 (issue #326): inject OAuth client credentials at compile time.
# Secrets.swift is the canonical source for Secrets.clientID/clientSecret;
# it is overwritten here so values are baked into the binary and never read
# from the runtime environment.
# ---------------------------------------------------------------------------
CLIENT_ID="${RUNNERBAR_CLIENT_ID:-PLACEHOLDER_CLIENT_ID}"
CLIENT_SECRET="${RUNNERBAR_CLIENT_SECRET:-PLACEHOLDER_CLIENT_SECRET}"

cat > Sources/RunnerBar/Secrets.swift <<SWIFT
// MARK: - Secrets
//
// ⚠️  DO NOT EDIT BY HAND.
// Generated by build.sh — overwritten on every build.

enum Secrets {
    static let clientID: String = "${CLIENT_ID}"
    static let clientSecret: String = "${CLIENT_SECRET}"
}
SWIFT

echo "→ Compiling universal binary..."
swift build -c release --arch arm64 --arch x86_64

echo "→ Assembling .app bundle..."
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/$APP_NAME.app/Contents/MacOS"
mkdir -p "$OUT_DIR/$APP_NAME.app/Contents/Resources"

cp ".build/apple/Products/Release/$APP_NAME" \
   "$OUT_DIR/$APP_NAME.app/Contents/MacOS/"
cp "Resources/Info.plist" \
   "$OUT_DIR/$APP_NAME.app/Contents/"

echo "→ Ad-hoc signing..."
codesign --force --deep --sign - "$OUT_DIR/$APP_NAME.app"

echo "→ Zipping..."
ditto -c -k --keepParent \
    "$OUT_DIR/$APP_NAME.app" \
    "$OUT_DIR/RunnerBar.zip"

echo "$VERSION" > "$OUT_DIR/version.txt"

echo "✓ Done — dist/RunnerBar.zip is ready"
