// RunnerBarUITests.swift
// RunnerBarUITests
//
// Passive AX smoke tests — no mouse movement, no window focus stealing.
// Runs on the self-hosted runner via xcodebuild.
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// Design constraints:
//   • XCUIApplication on macOS is NOT headless — any click/type moves the real
//     mouse cursor and steals focus on the active desktop session.
//   • All tests here are READ-ONLY: they only query the AX tree, never synthesise
//     input events. This keeps CI safe to run on a shared/active machine.
//
// ⚠️ XCUIApplication must be initialised with the bundle ID (not default init)
//    to avoid Xcode 26 path resolution bug with LSUIElement apps.
// ⚠️ Do NOT set XCTTargetAppPath in project.yml scheme env — Xcode 26 strips
//    the .app extension, causing a fatal "bundle ID couldn't be read" error.
// ⚠️ During UI tests, AppDelegate calls setActivationPolicy(.regular) in
//    applicationWillFinishLaunching so the app runs as .runningForeground.
//    This makes app.windows and all AX queries work normally.
// ⚠️ To open the panel in CI (no mouse available), set OPEN_PANEL_ON_LAUNCH=1
//    in launchEnvironment. The app positions the panel with setFrameOrigin+orderFront
//    at .floating level (NOT openPanel() — that requires a real status item position).

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication(bundleIdentifier: "dev.eonist.runnerbar")
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    // MARK: - Smoke tests

    /// App reaches .runningForeground because UI_TESTING sets .regular activation policy.
    func testAppLaunchesWithoutCrashing() {
        XCTAssertTrue(
            app.wait(for: .runningForeground, timeout: 5),
            "App should reach .runningForeground (setActivationPolicy(.regular) in UI_TESTING)"
        )
    }

    /// NSStatusItem is present in the menu bar AX tree after launch.
    func testStatusBarItemExists() {
        XCTAssertTrue(
            app.statusItems.firstMatch.waitForExistence(timeout: 3),
            "Status bar item should be visible in the AX tree"
        )
    }

    // MARK: - Panel UI test

    /// The panel window appears and contains the expected header elements.
    /// Uses OPEN_PANEL_ON_LAUNCH to trigger display without a mouse click.
    func testPanelOpensAndShowsWorkflowsSection() {
        app.terminate()
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launchEnvironment["OPEN_PANEL_ON_LAUNCH"] = "1"
        app.launch()

        XCTAssertTrue(
            app.wait(for: .runningForeground, timeout: 5),
            "App should reach .runningForeground"
        )

        let panel = app.windows.firstMatch
        XCTAssertTrue(
            panel.waitForExistence(timeout: 10),
            "Panel should appear in app.windows after OPEN_PANEL_ON_LAUNCH"
        )

        let workflowsHeader = app.staticTexts["Workflows"]
        XCTAssertTrue(
            workflowsHeader.waitForExistence(timeout: 5),
            "Panel content should contain the 'Workflows' section header"
        )
    }
}
