// RunnerBarUITests.swift
// RunnerBarUITests
//
// UI tests for RunnerBar using real mouse interaction.
// Runs on the self-hosted runner via xcodebuild.
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// Design:
//   • AppDelegate calls setActivationPolicy(.regular) + activate() when
//     UI_TESTING is set, so the app runs as a normal foreground app.
//   • This means app.buttons, app.staticTexts etc. all work.
//   • The status item can be clicked normally to open the panel.
//
// ⚠️ XCUIApplication must be initialised with the bundle ID (not default init)
//    to avoid Xcode 26 path resolution bug.
// ⚠️ Do NOT set XCTTargetAppPath in project.yml scheme env — Xcode 26 strips
//    the .app extension, causing a fatal "bundle ID couldn't be read" error.
//
// ⚠️ app.windows does NOT enumerate NSPanel with [.borderless, .nonactivatingPanel].
//    Borderless non-activating panels appear under app.otherElements, not app.windows.
//    ❌ NEVER use app.windows to find the RunnerBar panel.
//    ✓ Use app.staticTexts / app.buttons to verify panel content directly.
//
// ⚠️ The Settings gear button and the Settings back button both have AX label
//    "Settings" — they are never on-screen simultaneously so app.buttons["Settings"]
//    is unambiguous in each test. If that changes, add
//    .accessibilityIdentifier("settings-back-button") to the back button and
//    query via app.buttons.matching(identifier:).firstMatch instead.
//
// ⚠️ Text("Settings") in the SettingsView header is nested inside a Button —
//    it does NOT appear as a standalone staticText in the AX tree.
//    ❌ NEVER assert app.staticTexts["Settings"] to verify Settings is open.
//    ✓ Use app.staticTexts["Active local runners"] — first unconditional section header.
//
// ⚠️ isHittable is always false for .buttonStyle(.plain) buttons inside a
//    .nonactivatingPanel — the panel never becomes key, so XCTest cannot
//    verify hit-testability at the window level.
//    ❌ NEVER wait for isHittable on panel buttons.
//
// ⚠️ .click() on elements inside a borderless .nonactivatingPanel fires a CGEvent
//    in Quartz screen coordinates (bottom-left origin). The AX frame is in
//    HIServices coordinates (top-left origin). The panel never becomes key so
//    the window-level coordinate transform is never applied — clicks land at
//    the Y-flipped screen position, outside the panel.
//    ❌ NEVER call .click() directly on elements inside the panel.
//    ✓ Use .coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5)).click()
//      Normalized-offset clicks are relative to the element's own bounds,
//      bypassing the absolute coordinate-space flip entirely.

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication(bundleIdentifier: "dev.eonist.runnerbar")
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
        XCTAssertTrue(app.wait(for: .runningForeground, timeout: 5))
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    // MARK: - Helpers

    /// Waits for element to exist, then clicks its centre via a normalised-offset
    /// coordinate. This bypasses the Quartz/HIServices Y-axis flip that causes
    /// direct .click() calls to land outside a borderless .nonactivatingPanel.
    private func tapButton(_ element: XCUIElement, timeout: TimeInterval = 5) {
        XCTAssertTrue(element.waitForExistence(timeout: timeout),
                      "Element '\(element.label)' should exist before tapping")
        element.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5)).click()
    }

    // MARK: - Settings navigation

    /// Full settings flow:
    /// open panel → assert main content →
    /// open settings → verify all section headers →
    /// open Add Runner sheet → verify + cancel →
    /// open Add Scope sheet → verify + cancel →
    /// back to main → confirm WORKFLOWS visible, Settings gone.
    func testSettingsNavigationFlow() {
        // ── Open panel ────────────────────────────────────────────────
        let statusItem = app.statusItems.firstMatch
        XCTAssertTrue(statusItem.waitForExistence(timeout: 3))
        statusItem.click()
        XCTAssertTrue(
            app.staticTexts["WORKFLOWS"].waitForExistence(timeout: 5),
            "Main panel must show WORKFLOWS section header after status item click"
        )

        // ── 1. Open Settings ──────────────────────────────────────────
        tapButton(app.buttons["Settings"])
        // Text("Settings") is inside the back Button — not a standalone staticText.
        // Proof-of-arrival: first unconditional section header in SettingsView.
        XCTAssertTrue(app.staticTexts["Active local runners"].waitForExistence(timeout: 5),
                      "Active local runners section header")
        XCTAssertTrue(app.staticTexts["Remote runner scopes"].exists,
                      "Remote scopes section header")
        XCTAssertTrue(app.staticTexts["Notifications"].exists,
                      "Notifications section header")
        XCTAssertTrue(app.staticTexts["General"].exists,
                      "General section header")
        XCTAssertTrue(app.staticTexts["Account"].exists,
                      "Account section header")
        XCTAssertTrue(app.staticTexts["About"].exists,
                      "About section header")

        // ── 2. Add Runner sheet ───────────────────────────────────────
        tapButton(app.buttons["Add a new runner"])
        XCTAssertTrue(app.staticTexts["Add runner"].waitForExistence(timeout: 3),
                      "Add Runner sheet title should appear")
        XCTAssertTrue(app.buttons["Add new"].exists)
        XCTAssertTrue(app.buttons["Add pre-existing"].exists)
        tapButton(app.buttons["Cancel"])
        XCTAssertTrue(app.staticTexts["Active local runners"].waitForExistence(timeout: 3),
                      "Should return to Settings after cancelling Add Runner sheet")

        // ── 3. Add Scope sheet ────────────────────────────────────────
        tapButton(app.buttons["Add a remote scope"])
        XCTAssertTrue(app.staticTexts["Add remote scope"].waitForExistence(timeout: 3),
                      "Add Scope sheet title should appear")
        XCTAssertTrue(app.buttons["Organisation"].exists)
        XCTAssertTrue(app.buttons["Repository"].exists)
        tapButton(app.buttons["Cancel"])
        XCTAssertTrue(app.staticTexts["Active local runners"].waitForExistence(timeout: 3),
                      "Should return to Settings after cancelling Add Scope sheet")

        // ── 4. Back to main ───────────────────────────────────────────
        tapButton(app.buttons["Settings"])
        XCTAssertTrue(
            app.staticTexts["WORKFLOWS"].waitForExistence(timeout: 5),
            "WORKFLOWS section header should reappear after navigating back to main"
        )
        XCTAssertFalse(
            app.staticTexts["Active local runners"].exists,
            "Settings content must not be visible after going back to main"
        )
    }
}
