// RunnerBarUITests.swift
// RunnerBarUITests
//
// UI tests for RunnerBar using real mouse interaction.
// Runs on the self-hosted runner via xcodebuild.
// The ephemeral .xcodeproj is generated by XcodeGen from project.yml at CI time.
//
// Design:
//   • AppDelegate calls setActivationPolicy(.regular) + activate() when
//     UI_TESTING is set, so the app runs as a normal foreground app.
//   • This means app.windows, app.buttons, app.staticTexts etc. all work.
//   • The status item can be clicked normally to open the panel.
//
// ⚠️ XCUIApplication must be initialised with the bundle ID (not default init)
//    to avoid Xcode 26 path resolution bug.
// ⚠️ Do NOT set XCTTargetAppPath in project.yml scheme env — Xcode 26 strips
//    the .app extension, causing a fatal "bundle ID couldn't be read" error.
//
// ⚠️ app.windows does NOT enumerate NSPanel with [.borderless, .nonactivatingPanel].
//    Borderless non-activating panels appear under app.otherElements, not app.windows.
//    ❌ NEVER use app.windows to find the RunnerBar panel.
//    ✓ Use app.staticTexts / app.otherElements to verify panel content directly.

import XCTest

final class RunnerBarUITests: XCTestCase {

    var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication(bundleIdentifier: "dev.eonist.runnerbar")
        app.launchEnvironment["UI_TESTING"] = "1"
        app.launch()
        XCTAssertTrue(app.wait(for: .runningForeground, timeout: 5))
    }

    override func tearDown() {
        app.terminate()
        super.tearDown()
    }

    // MARK: - Smoke tests

    /// App reaches .runningForeground because UI_TESTING sets .regular activation policy.
    func testAppLaunchesWithoutCrashing() {
        XCTAssertTrue(
            app.wait(for: .runningForeground, timeout: 5),
            "App should be running in the foreground"
        )
    }

    /// NSStatusItem is present in the menu bar after launch.
    func testStatusBarItemExists() {
        XCTAssertTrue(
            app.statusItems.firstMatch.waitForExistence(timeout: 3),
            "Status bar item should exist"
        )
    }

    // MARK: - Panel tests

    /// Clicking the status item opens the panel and shows the Workflows section.
    ///
    /// The panel is an NSPanel with [.borderless, .nonactivatingPanel] style mask.
    /// Borderless non-activating panels are NOT enumerated by app.windows in XCUITest.
    /// We verify the panel opened by waiting for content directly via app.staticTexts.
    func testPanelOpensAndShowsWorkflowsSection() {
        let statusItem = app.statusItems.firstMatch
        XCTAssertTrue(statusItem.waitForExistence(timeout: 3), "Status item should exist")
        statusItem.click()

        // ❌ Do NOT use app.windows.firstMatch — borderless nonactivating NSPanel
        //    never appears in app.windows. Query content directly instead.
        XCTAssertTrue(
            app.staticTexts["WORKFLOWS"].waitForExistence(timeout: 5),
            "Panel should contain the 'WORKFLOWS' section header after clicking status item"
        )
    }
}
